### ISSUE TITLE
 No such file or directory: './source/cls2ind.pkl'

### ISSUE THREAD

**Issue by mofang2016** [cizhenshi/TianchiGuangdong2019_2th#1]
作者可以解释一下这个文件怎么获取吗？
代码在tools/PrepareData.py中
def generate_coco(annos, out_file):
    cls2ind = mmcv.load("./source/cls2ind.pkl")
    ind2cls = mmcv.load("./source/ind2cls.pkl")

**Comment by cizhenshi** [comment]
这是类别和id的映射，上传的时候忘记传了
https://pan.baidu.com/s/1f8a--FEpM22j-vrt4zVSdw
提取码：h5a5

**Comment by mofang2016** [comment]
好的，谢谢。
不知道作者方便更新不；另外在调试过程中发现几个小小的error,比如：
![图片](https://user-images.githubusercontent.com/24251325/70375852-c8283880-193d-11ea-9303-d8082455ba6b.png)

**Comment by cizhenshi** [comment]
感谢提醒，已修正

**Comment by mofang2016** [comment]
能加下联系方式吗，最近在跑这个代码，还是遇到一些问题，有些文件找不到------------------ 原始邮件 ------------------
发件人: "cizhenshi"<notifications@github.com>
发送时间: 2019年12月8日(星期天) 下午2:52
收件人: "cizhenshi/TianchiGuangdong2019_2th"<TianchiGuangdong2019_2th@noreply.github.com>;
抄送: "mofang2016"<3074222026@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [cizhenshi/TianchiGuangdong2019_2th]  No such file or directory:'./source/cls2ind.pkl' (#1)



感谢提醒，已修正
 
&mdash;

**Comment by cizhenshi** [comment]
有问题github或者直接发邮件给我都可以，我看到就会回的

**Comment by mofang2016** [comment]
> 有问题github或者直接发邮件给我都可以，我看到就会回的
现在训练了作者ResNext101+DCNv2模型，得到每张图片有300个预测框，如果我想把框show在图像上，需要经过阈值筛选？？作者是怎么处理的呢

**Comment by cizhenshi** [comment]
得到框之后 用opencv 什么的就可以画在图像上了
mmdetection 本身也有一些可视化函数  可以看一下相关代码

**Comment by mofang2016** [comment]
嗯，但是300个框全部画上去吗？

**Comment by cizhenshi** [comment]
这个你自己设置阈值来控制吧    一般框越多map 越高
