### ISSUE TITLE
global context

### ISSUE THREAD

**Issue by yeungchenwa** [cizhenshi/TianchiGuangdong2019_2th#17]
请问那个global context的实现在这个代码里面是不是没有呢，谢谢

**Comment by ganjf** [comment]
> 请问那个global context的实现在这个代码里面是不是没有呢，谢谢
`bbox_roi_extractor=dict(
        type='SingleRoIExtractor',
        roi_layer=dict(type='RoIAlign', out_size=7, sample_num=2),
        out_channels=256,
        add_context=True,
        featmap_strides=[4, 8, 16, 32]),`

**Comment by cizhenshi** [comment]
有实现，add_context=True的情况下会触发global_context
