### ISSUE TITLE
对于正常图像（不包含缺陷）图像怎么处理的呢

### ISSUE THREAD

**Issue by Chen-Song** [cizhenshi/TianchiGuangdong2019_2th#18]
您好，请问对于正常图像（不包含缺陷）图像怎么处理的呢？看了下代码好像直接给设置成False了？请问您当时使用的mmdetection的版本是哪个呢？

**Comment by Chen-Song** [comment]
请问这个Fast Reboost机制是什么意思呢？
![image](https://user-images.githubusercontent.com/38151697/109388278-1cec1080-7941-11eb-824e-90ec67f05937.png)

**Comment by cizhenshi** [comment]
fast reboost实际上就是说预测的时候 同一个花色对应的模板（即没有瑕疵的正常样本）只需要预测一次得到最终的结果，不需要每次都和瑕疵图像一起预测，以此来达到节约预测时间的目的。
