### ISSUE TITLE
关于验证集数据

### ISSUE THREAD

**Issue by amandaluof** [cizhenshi/TianchiGuangdong2019_2th#19]
哈喽 ！最近希望复现作者的实验并比较不同的模板使用方式的差异。请问能否提供temp_cls.pkl 或者是val_0.json 的对应数据，因为需要在一个验证集上评估不同模型～

**Comment by cizhenshi** [comment]
数据无法提供，而且在实际中由于验证集并不准确，实际上并没有根据验证集做太多调整，可以根据训练集自行分割验证集，只需要注意隔离花色即可。
