### ISSUE TITLE
Context  ROI  erro     help

### ISSUE THREAD

**Issue by heartInsert** [cizhenshi/TianchiGuangdong2019_2th#6]
Hello , 我想试验这份repository中的contextROI，所以把直接把`SingleRoIExtractor`粘到我的文件中了，但是看起来116行的加法` roi_feats_t[rois_[:, 0] == j] += context[i][j]`是个inplace操作，我注释后才能运行，即使改成`roi_feats_t[rois_[:, 0] == j] = roi_feats_t[rois_[:, 0] == j] + context[i][j]`　仍然报了同样的错误。
报错如下：
`RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [38, 256, 7, 7]], which is output 0 of IndexPutBackward, is at version 5; expected version 4 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True)`
－－－－－－－－－－－－－－－－
请问你们在feat进入SingleRoIExtractor之前，做了什么特殊的操作吗?
Thanks for your help.

**Comment by cizhenshi** [comment]
没有其他特殊操作了，就是一个全局平均池化 然后和原来的特征相加

**Comment by whut2962575697** [comment]
> Hello , 我想试验这份repository中的contextROI，所以把直接把`SingleRoIExtractor`粘到我的文件中了，但是看起来116行的加法` roi_feats_t[rois_[:, 0] == j] += context[i][j]`是个inplace操作，我注释后才能运行，即使改成`roi_feats_t[rois_[:, 0] == j] = roi_feats_t[rois_[:, 0] == j] + context[i][j]`　仍然报了同样的错误。
> 报错如下：
> `RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [38, 256, 7, 7]], which is output 0 of IndexPutBackward, is at version 5; expected version 4 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True)`
> －－－－－－－－－－－－－－－－
> 请问你们在feat进入SingleRoIExtractor之前，做了什么特殊的操作吗?
> Thanks for your help.

我遇到了同样的问题，请问你解决了吗

**Comment by heartInsert** [comment]
@cizhenshi 你猜QAQ

**Comment by whut2962575697** [comment]
哈哈，已经搞定了
